### ISSUE TITLE
Cross-Referencing

### ISSUE THREAD

**Issue by davidfaraci** [opentower/populus-viewer#58]
It would be nice to be able to:
- Link to another page of a PDF within a comment
- Link to another annotation within a comment

**Comment by gleachkr** [comment]
OK, internal links (links that change only the query parameters) in messages are now handled by the app rather than the browser. So if you include a link (using markdown, like `[here](example.com)`) to a page or another annotation, you'll get redirected there without a reload.

Let's try this out a bit, and open other issues if we need, e.g. a "copy link" button on the annotation listing.
